//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionStoreWinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FashionStoreWinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all WHs.
        /// </summary>
        internal static string ALL_WAREHOUSES_SHORT {
            get {
                return ResourceManager.GetString("ALL_WAREHOUSES_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion Store.
        /// </summary>
        internal static string APP_BRAND {
            get {
                return ResourceManager.GetString("APP_BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel sale of &quot;{0}&quot; with price of {1}?.
        /// </summary>
        internal static string ASK_CANCEL_SALE {
            get {
                return ResourceManager.GetString("ASK_CANCEL_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete object?.
        /// </summary>
        internal static string ASK_DELETE_OBJECT {
            get {
                return ResourceManager.GetString("ASK_DELETE_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Do you wish to remove all SKU &quot;{0}&quot; with purchasing price of {1}? If this SKU is not present in any other warehouses, it will be completely removed..
        /// </summary>
        internal static string ASK_DELETE_SKU {
            get {
                return ResourceManager.GetString("ASK_DELETE_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form can have unsaved data. Proceed with new action?.
        /// </summary>
        internal static string ASK_PROCEED_AND_ABANDON_FORM_DATA {
            get {
                return ResourceManager.GetString("ASK_PROCEED_AND_ABANDON_FORM_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all entered values?.
        /// </summary>
        internal static string ASK_RESET_ALL_ENTERED_VALUES {
            get {
                return ResourceManager.GetString("ASK_RESET_ALL_ENTERED_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the full list of SKUs in this stock?.
        /// </summary>
        internal static string ASK_SHOW_ALL_SKUS_IN_THIS_STOCK {
            get {
                return ResourceManager.GetString("ASK_SHOW_ALL_SKUS_IN_THIS_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such SKU. Start creating new SKU with such name?.
        /// </summary>
        internal static string ASK_WHETHER_TO_CREATE_NEW_SKU {
            get {
                return ResourceManager.GetString("ASK_WHETHER_TO_CREATE_NEW_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string ATTENTION {
            get {
                return ResourceManager.GetString("ATTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION! The price is 0, so item is sold for free..
        /// </summary>
        internal static string ATTENTION_ZERO_PRICE {
            get {
                return ResourceManager.GetString("ATTENTION_ZERO_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed..
        /// </summary>
        internal static string BACKUP_COMPLETED {
            get {
                return ResourceManager.GetString("BACKUP_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup storage device is not attached..
        /// </summary>
        internal static string BACKUP_FOLDER_NOT_EXISTS {
            get {
                return ResourceManager.GetString("BACKUP_FOLDER_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup folder is not set in the program settings..
        /// </summary>
        internal static string BACKUP_FOLDER_NOT_SET {
            get {
                return ResourceManager.GetString("BACKUP_FOLDER_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation.
        /// </summary>
        internal static string CANCELATION {
            get {
                return ResourceManager.GetString("CANCELATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose backup folder.
        /// </summary>
        internal static string CHOOSE_BACKUP_FOLDER {
            get {
                return ResourceManager.GetString("CHOOSE_BACKUP_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view, sell or move SKU ({0}).
        /// </summary>
        internal static string CLICK_TO_VIEW_SELL_MOVE_SKU {
            get {
                return ResourceManager.GetString("CLICK_TO_VIEW_SELL_MOVE_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {1} units of SKU &quot;{0}&quot; to warehouse {3}?.
        /// </summary>
        internal static string CONFIRM_MOVING_GOODS {
            get {
                return ResourceManager.GetString("CONFIRM_MOVING_GOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} has been selected.
        ///Continue?.
        /// </summary>
        internal static string CONFIRM_SELECTED_DATE {
            get {
                return ResourceManager.GetString("CONFIRM_SELECTED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string CONFIRMATION {
            get {
                return ResourceManager.GetString("CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purch.cost.
        /// </summary>
        internal static string COST_OF_PURCHASE_SHORT {
            get {
                return ResourceManager.GetString("COST_OF_PURCHASE_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error.
        /// </summary>
        internal static string CRITICAL_ERROR {
            get {
                return ResourceManager.GetString("CRITICAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error happened. This application will be closed now..
        /// </summary>
        internal static string CRITICAL_ERROR_MSG_COMMON1 {
            get {
                return ResourceManager.GetString("CRITICAL_ERROR_MSG_COMMON1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will help to find and fix the defect..
        /// </summary>
        internal static string CRITICAL_ERROR_MSG_COMMON2 {
            get {
                return ResourceManager.GetString("CRITICAL_ERROR_MSG_COMMON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please describe to the developer your actions right before this error happened..
        /// </summary>
        internal static string CRITICAL_ERROR_MSG_DESCRIBE_ACTIONS {
            get {
                return ResourceManager.GetString("CRITICAL_ERROR_MSG_DESCRIBE_ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the file which you&apos;ll see now, to the developer, with description of your actions right before this error happened..
        /// </summary>
        internal static string CRITICAL_ERROR_MSG_SEND_FILE {
            get {
                return ResourceManager.GetString("CRITICAL_ERROR_MSG_SEND_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current warehouse not selected..
        /// </summary>
        internal static string CURRENT_WAREHOUSE_NOT_SELECTED {
            get {
                return ResourceManager.GetString("CURRENT_WAREHOUSE_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed only integer positive number..
        /// </summary>
        internal static string ERR_PART_CELL_QTY {
            get {
                return ResourceManager.GetString("ERR_PART_CELL_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed only integer (without cents) non-negative number..
        /// </summary>
        internal static string ERR_PART_PRICE {
            get {
                return ResourceManager.GetString("ERR_PART_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string FAILURE {
            get {
                return ResourceManager.GetString("FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SKUs has been found. Because of memory constraints, it will be shown only {1} of them. For viewing all needed SKUs, please enter more precise search query..
        /// </summary>
        internal static string FOUND_TOO_MUCH {
            get {
                return ResourceManager.GetString("FOUND_TOO_MUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods has been moved..
        /// </summary>
        internal static string GOODS_HAS_BEEN_MOVED {
            get {
                return ResourceManager.GetString("GOODS_HAS_BEEN_MOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cost of purchase..
        /// </summary>
        internal static string INVALID_COST_OF_PURCHASE {
            get {
                return ResourceManager.GetString("INVALID_COST_OF_PURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cost of purchase. It should be an integer non-negative number..
        /// </summary>
        internal static string INVALID_COST_OF_PURCHASE_EXPLAINED {
            get {
                return ResourceManager.GetString("INVALID_COST_OF_PURCHASE_EXPLAINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID..
        /// </summary>
        internal static string INVALID_ID {
            get {
                return ResourceManager.GetString("INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid planned sell price..
        /// </summary>
        internal static string INVALID_SELL_PRICE {
            get {
                return ResourceManager.GetString("INVALID_SELL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SKU quantity is entered..
        /// </summary>
        internal static string INVALID_SKU_QTY_IS_ENTERED {
            get {
                return ResourceManager.GetString("INVALID_SKU_QTY_IS_ENTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SKU quantity is entered in cell {0}:{1}..
        /// </summary>
        internal static string INVALID_SKU_QTY_IS_ENTERED_IN_CELL {
            get {
                return ResourceManager.GetString("INVALID_SKU_QTY_IS_ENTERED_IN_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid price of sell per unit entered..
        /// </summary>
        internal static string INVALID_UNIT_PRICE_OF_SELL {
            get {
                return ResourceManager.GetString("INVALID_UNIT_PRICE_OF_SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string MESSAGE {
            get {
                return ResourceManager.GetString("MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not set..
        /// </summary>
        internal static string NAME_NOT_SET {
            get {
                return ResourceManager.GetString("NAME_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New date is the same as an old one, so we change nothing..
        /// </summary>
        internal static string NEW_DATE_IS_SAME_AS_OLD_ONE_SO_CHANGE_NOTHING {
            get {
                return ResourceManager.GetString("NEW_DATE_IS_SAME_AS_OLD_ONE_SO_CHANGE_NOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No row selected..
        /// </summary>
        internal static string NO_ROW_SELECTED {
            get {
                return ResourceManager.GetString("NO_ROW_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has been found..
        /// </summary>
        internal static string NOTHING_FOUND {
            get {
                return ResourceManager.GetString("NOTHING_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found..
        /// </summary>
        internal static string OBJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("OBJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to database is not set in settings..
        /// </summary>
        internal static string PATH_TO_DB_NOT_SET {
            get {
                return ResourceManager.GetString("PATH_TO_DB_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price stocks.
        /// </summary>
        internal static string PRICE_OF_STOCKS_SHORT {
            get {
                return ResourceManager.GetString("PRICE_OF_STOCKS_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program &quot;{0}&quot; is already launched. Probably, you clicked on its launcher twice..
        /// </summary>
        internal static string PROGRAM_ALREADY_LAUCHED {
            get {
                return ResourceManager.GetString("PROGRAM_ALREADY_LAUCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ver.{1}.
        /// </summary>
        internal static string PROGRAM_AND_VERSION {
            get {
                return ResourceManager.GetString("PROGRAM_AND_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string QTY_SHORT {
            get {
                return ResourceManager.GetString("QTY_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU quantity is too big, there is no such amount goods in this cell..
        /// </summary>
        internal static string QTY_TOO_BIG_FOR_GIVEN_CELL {
            get {
                return ResourceManager.GetString("QTY_TOO_BIG_FOR_GIVEN_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QUESTION {
            get {
                return ResourceManager.GetString("QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question about date.
        /// </summary>
        internal static string QUESTION_ABOUT_DATE {
            get {
                return ResourceManager.GetString("QUESTION_ABOUT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales number: {0}  Sum: {1}  Profit: {2}.
        /// </summary>
        internal static string SALES_SUMMARY_LABEL {
            get {
                return ResourceManager.GetString("SALES_SUMMARY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell price.
        /// </summary>
        internal static string SELL_PRICE_SHORT {
            get {
                return ResourceManager.GetString("SELL_PRICE_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        internal static string SIZES {
            get {
                return ResourceManager.GetString("SIZES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string SKU {
            get {
                return ResourceManager.GetString("SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU has been saved..
        /// </summary>
        internal static string SKU_HAS_BEEN_SAVED {
            get {
                return ResourceManager.GetString("SKU_HAS_BEEN_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU in stock ({0}).
        /// </summary>
        internal static string SKU_IN_STOCK {
            get {
                return ResourceManager.GetString("SKU_IN_STOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings require to reload the program to take effect..
        /// </summary>
        internal static string SOME_SETTINGS_REQUIRE_TO_RELOAD_PROGRAM {
            get {
                return ResourceManager.GetString("SOME_SETTINGS_REQUIRE_TO_RELOAD_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTALS.
        /// </summary>
        internal static string TOTALS_CAP {
            get {
                return ResourceManager.GetString("TOTALS_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete object, it has subordinate objects..
        /// </summary>
        internal static string UNABLE_DELETE_OBJECT_HAS_CHILDREN {
            get {
                return ResourceManager.GetString("UNABLE_DELETE_OBJECT_HAS_CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete object. Technical failure code: {0}..
        /// </summary>
        internal static string UNABLE_DELETE_OBJECT_TECHNICAL_CODE {
            get {
                return ResourceManager.GetString("UNABLE_DELETE_OBJECT_TECHNICAL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save a report file. Probably, its old copy is opened by another program - if so, you need to close it first. If it do not help, try to reboot your computer (or switch it off and then on)..
        /// </summary>
        internal static string UNABLE_TO_CREATE_REPORT_LONG {
            get {
                return ResourceManager.GetString("UNABLE_TO_CREATE_REPORT_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string WARNING_EXCLAMATION {
            get {
                return ResourceManager.GetString("WARNING_EXCLAMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be sold {0} units of &quot;{1}&quot; with price of {2} per unit..
        /// </summary>
        internal static string WILL_BE_SOLD_DETAILS {
            get {
                return ResourceManager.GetString("WILL_BE_SOLD_DETAILS", resourceCulture);
            }
        }
    }
}
